name: Build and release

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: 'ubuntu:22.04' # start with a clean environment instead of the default github runner for higher reproducibility
    steps:
    - uses: actions/checkout@v4
    - name: preinstall
      run: apt update && apt -y install sudo wget rsync g++ make cmake
    - name: create_dirs
      run: mkdir -p ${{ github.workspace }}/my_rel ${{ github.workspace }}/my_build
    - name: configure_and_make
      run: ./admin/builders/ubuntu64_build.sh -s `pwd`/.. -r ${{ github.workspace }}/my_rel -b ${{ github.workspace }}/my_build -g
# Skip tests for now
#    - name: test
#      run: cd ../my_build/maracluster && sudo make install && make test ARGS="-V"
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-packages
        path: ${{ github.workspace }}/my_rel

  build-fedora:
    runs-on: ubuntu-latest
    container: 'fedora:41'
    steps:
    - uses: actions/checkout@v4
    - name: preinstall
      run: dnf install -y wget rsync make
    - name: create_dirs
      run: mkdir -p ${{ github.workspace }}/my_rel ${{ github.workspace }}/my_build
    - name: configure_and_make
      run: ./admin/builders/fedora64_build.sh -s `pwd`/.. -r ${{ github.workspace }}/my_rel -b ${{ github.workspace }}/my_build -g
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: fedora-packages
        path: ${{ github.workspace }}/my_rel

  build-tarball:
    runs-on: ubuntu-latest
    container: 'ubuntu:22.04' # start with a clean environment instead of the default github runner for higher reproducibility
    steps:
    - uses: actions/checkout@v4
    - name: preinstall
      run: apt update && apt -y install sudo wget rsync g++ make cmake
    - name: create_dirs
      run: mkdir -p ${{ github.workspace }}/my_rel ${{ github.workspace }}/my_build
    - name: configure_and_make
      run: ./admin/builders/tarball64_build.sh -s `pwd`/.. -r ${{ github.workspace }}/my_rel -b ${{ github.workspace }}/my_build -g
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: tarball-packages
        path: ${{ github.workspace }}/my_rel

  build-osx:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: create_dirs
      run: mkdir -p ${{ github.workspace }}/my_rel ${{ github.workspace }}/my_build
    - name: configure_and_make
      run: admin/builders/osx64_build.sh -s `pwd`/.. -r ${{ github.workspace }}/my_rel -b ${{ github.workspace }}/my_build -g
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: osx-packages
        path: ${{ github.workspace }}/my_rel

  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v4
    - name: create_dirs
      run: CD ${{ github.workspace }} || MKDIR my_rel my_build
    - name: configure_and_make
      run: |
        CD ..
        SET base_dir=%cd%
        ECHO %base_dir%
        CALL maracluster\admin\builders\nativew64_build.bat -s %base_dir% -r %base_dir%\my_rel -b %base_dir%\my_build -g
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: win64-packages
        path: ${{ github.workspace }}\my_rel

  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-fedora, build-tarball, build-osx, build-win64]
    if: startsWith(github.ref, 'refs/tags/rel-')
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - run : |
        ls -R
        mkdir packages
        tar -czvf packages/ubuntu.tar.gz -C ubuntu-packages $(ls ubuntu-packages)
        tar -czvf packages/centos.tar.gz -C centos-packages $(ls centos-packages)
        tar -czvf packages/fedora.tar.gz -C fedora-packages $(ls fedora-packages)
        tar -czvf packages/tarball.tar.gz -C tarball-packages $(ls tarball-packages)
        zip -j -r packages/osx.zip osx-packages/*
        zip -j -r packages/win64.zip win64-packages/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v4
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/*
        tag: ${{ github.ref }}
        overwrite: false
        file_glob: true
