name: Build and release

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            container: 'ubuntu:18.04'
            preinstall: apt update && apt -y install sudo wget rsync g++ make cmake
            build_script: ubuntu64_build.sh
          - name: fedora
            container: 'fedora:35'
            preinstall: dnf install -y wget rsync make
            build_script: fedora64_build.sh
          - name: centos
            container: 'centos:centos7'
            preinstall: yum install -y sudo scl-utils wget make
            build_script: centos64_build.sh
          - name: tarball
            container: 'ubuntu:18.04'
            preinstall: apt update && apt -y install sudo wget rsync g++ make cmake
            build_script: tarball64_build.sh
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4
    - name: preinstall
      run: ${{ matrix.preinstall }}
    - name: create_dirs
      run: mkdir -p ../my_rel ../my_build
    - name: configure_and_make
      run: ./admin/builders/${{ matrix.build_script }} -s `pwd`/.. -r `pwd`/../my_rel -b `pwd`/../my_build -g
# Skip tests for now
#    - name: test
#      run: cd ../my_build/maracluster && sudo make install && make test ARGS="-V"
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-packages
        path: ../my_rel

  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: create_dirs
      run: mkdir -p ../my_rel ../my_build
    - name: configure_and_make
      run: admin/builders/osx64_build.sh -s `pwd`/.. -r `pwd`/../my_rel -b `pwd`/../my_build -g
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: osx-packages
        path: ../my_rel

  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v4
    - name: create_dirs
      run: CD .. || MKDIR my_rel my_build
    - name: configure_and_make
      run: |
        CD ..
        SET base_dir=%cd%
        ECHO %base_dir%
        CALL maracluster\admin\builders\nativew64_build.bat -s %base_dir% -r %base_dir%\my_rel -b %base_dir%\my_build -g
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: win64-packages
        path: ..\my_rel

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-osx, build-win64]
    if: startsWith(github.ref, 'refs/tags/rel-')
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - run : |
        ls -R
        mkdir packages
        tar -czvf packages/ubuntu.tar.gz -C artifacts/ubuntu-packages $(ls artifacts/ubuntu-packages)
        tar -czvf packages/centos.tar.gz -C artifacts/centos-packages $(ls artifacts/centos-packages)
        tar -czvf packages/fedora.tar.gz -C artifacts/fedora-packages $(ls artifacts/fedora-packages)
        tar -czvf packages/tarball.tar.gz -C artifacts/tarball-packages $(ls artifacts/tarball-packages)
        zip -j -r packages/osx.zip artifacts/osx-packages/*
        zip -j -r packages/win64.zip artifacts/win64-packages/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/*
        tag: ${{ github.ref }}
        overwrite: false
        file_glob: true
